name: verso

deployment:
  image:
    repository: patil16nit/microdigi-reverse
    tag: v3
    pullPolicy: IfNotPresent

  replicaCount: 1
  environment:
    - name  : base_url
      key   : BASE_URL
      value : elm.stg.svc.cluster.local
  ports:
    - name: public
      port: 3010
    - name: private
      port: 3011
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 128Mi
