apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name  }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    svc: {{ .Values.name }}
    chart: {{ template "verso.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: http
      targetPort: 80
      port: 80
      protocol: TCP
  selector:
    app: {{ .Values.name }}