apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name  }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    svc: {{ .Values.name }}
    chart: {{ template "random.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - nodePort: 30501
      protocol: TCP
      targetPort: 80
      port: 80
  selector:
    app: {{ .Values.name }}